apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-test-app
  labels:
    app: scale-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-test-app
  template:
    metadata:
      labels:
        app: scale-test-app
    spec:
       containers:
       - name: scale-test-app
         image: ghcr.io/yandex-practicum/scaletestapp:latest
         ports:
         - containerPort: 8080
         resources:
           requests:
             memory: "30Mi"
           limits:
             memory: "30Mi"
