apiVersion: v1
kind: Service
metadata:
  name: scale-test-app-service
  labels:
    app: scale-test-app
spec:
  selector:
    app: scale-test-app
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http

